from pathlib import Path
import re
FILES=[f'bolum-{n}.html' for n in range(26,33)]
STYLE='''<style id="cilt2-first25-style">*{box-sizing:border-box}body{margin:0;background:#050506;color:#fff;font-family:'Cormorant Garamond',Georgia,serif}.main{margin-left:215px;width:calc(100% - 215px);min-height:100vh}.topbar{height:78px;margin:0 42px;border-bottom:1px solid rgba(255,255,255,.1);display:flex;align-items:center;gap:12px;font-family:Inter,sans-serif;font-size:12px;letter-spacing:.08em;color:#fff}.topbar span:last-child{color:#d00000}.reader{max-width:1280px;margin:auto;padding:42px 42px 70px}.heading{min-height:205px;text-align:left}.chapter-label,.label,.kicker{color:#d00000;font-family:Inter,sans-serif;font-size:12px;letter-spacing:.2em;margin-bottom:13px;font-weight:500}.title,.heading h1{font-size:68px;line-height:.9;font-weight:500;color:#fff;margin:0;text-shadow:0 0 24px rgba(150,0,0,.22);font-family:'Cormorant Garamond',Georgia,serif}.number,.accent{display:none}.divider{height:1px;background:linear-gradient(90deg,rgba(255,255,255,.3),rgba(255,255,255,.03));margin:30px 0}.divider:after{content:'◆';display:block;text-align:center;color:#b40000;font-size:11px;transform:translateY(-8px)}article,.content{font-size:19px;line-height:1.7;padding:4px 0;color:#fff;font-family:'Cormorant Garamond',Georgia,serif}article p,.content p{margin:0 0 1.05em;font-weight:400}.dialogue{margin:1.15em 0!important;padding:11px 16px!important;border-left:2px solid rgba(255,255,255,.28);background:linear-gradient(90deg,rgba(255,255,255,.035),transparent);color:#fff!important;font-weight:400!important}.dialogue .speaker{display:block;color:#fff;font-family:Inter,sans-serif;font-size:10px;font-weight:600!important;letter-spacing:.17em;margin-bottom:5px}.dialogue .speech{display:block;color:#fff;font-family:'Cormorant Garamond',Georgia,serif;font-size:19px;font-weight:400!important;line-height:1.7}.reading-bar{display:none!important}.nav{display:grid;grid-template-columns:1fr .7fr 1fr;gap:10px;margin-top:48px}.nav a{min-height:70px;border:1px solid rgba(255,255,255,.12);padding:15px 18px;color:#fff;text-decoration:none;font-family:Inter,sans-serif;font-size:12px;display:flex;flex-direction:column;justify-content:center}.nav small{color:#d00000;font-size:9px;letter-spacing:.18em;margin-bottom:7px}.next{text-align:right}.next small{margin-left:auto}.scene-break,.scene,.break{color:#b40000;text-align:center}@media(max-width:950px){.main{margin-left:0;width:100%}.topbar{margin:0 22px}.reader{padding:28px 22px 60px}.heading{min-height:auto}.title,.heading h1{font-size:56px}.nav{grid-template-columns:1fr}.next{text-align:left}.next small{margin-left:0}}@media(max-width:600px){.topbar{height:60px;font-size:10px}.reader{padding:24px 16px 50px}.title,.heading h1{font-size:50px}article,.content{font-size:18px;line-height:1.75}.dialogue .speech{font-size:18px;line-height:1.75}}</style>'''
SCRIPT='''<script id="cilt2-first25-normalizer">(function(){const main=document.querySelector('.main');if(!main)return;const chapter=(document.title.match(/Bölüm\\s+(\\d+)/i)||[])[1]||'';const old=main.querySelector('.reading-bar');if(old)old.remove();if(!main.querySelector('.topbar')){const bar=document.createElement('div');bar.className='topbar';bar.innerHTML='<span>ANA SAYFA</span><b>/</b><span>BÖLÜMLER</span><b>/</b><span>BÖLÜM '+chapter.padStart(2,'0')+'</span>';main.insertBefore(bar,main.firstChild)}const reader=main.querySelector('.reader');if(!reader)return;if(!reader.querySelector('.divider')){const d=document.createElement('div');d.className='divider';const first=reader.querySelector('article');if(first)reader.insertBefore(d,first)}const article=reader.querySelector('article');if(!article)return;let ps=[...article.querySelectorAll('p.dialogue')];for(let i=0;i<ps.length-1;i++){const a=ps[i],b=ps[i+1],at=a.textContent.trim(),bt=b.textContent.trim();if(/^[^—:]{1,50}:$/.test(at)&&/^—/.test(bt)){const speaker=at.slice(0,-1).trim();a.innerHTML='<span class="speaker">'+speaker.toUpperCase()+'</span><span class="speech">'+bt+'</span>';a.className='dialogue';b.remove();ps=ps.filter(x=>x!==b);i--}}if(chapter==='27'){let speaker='ARAS';[...article.querySelectorAll('p.dialogue')].forEach(p=>{const t=p.textContent.trim();if(/^—/.test(t)){p.innerHTML='<span class="speaker">'+speaker+'</span><span class="speech">'+t+'</span>';speaker=speaker==='ARAS'?'KILAVUZ':'ARAS'}})}article.querySelectorAll('.dialogue').forEach(d=>{const sp=d.querySelector('.speaker'),speech=d.querySelector('.speech');if(sp)sp.style.fontWeight='600';if(speech)speech.style.fontWeight='400'})})();</script>'''
for fn in FILES:
 p=Path(fn)
 if not p.exists(): continue
 s=p.read_text(encoding='utf-8')
 s=re.sub(r'<style id="cilt2-first25-style">.*?</style>','',s,flags=re.S)
 s=s.replace('</head>',STYLE+'</head>')
 s=re.sub(r'<script id="cilt2-first25-normalizer">.*?</script>','',s,flags=re.S)
 s=s.replace('</body>',SCRIPT+'</body>')
 p.write_text(s,encoding='utf-8')
